#!/usr/bin/env bash
# SessionStart hook: inject Gerendo encryption rules into session context.
cat <<'EOF'
[GERENDO ENCRYPTION RULES — ALWAYS APPLY]

Sensitive content/PII columns are encrypted at rest with AES-256-GCM. Master key
in GERENDO_MASTER_KEY env var (Vercel + .env.local). All plaintext counterparts
have been DROPPED — only the _enc bytea columns exist now.

WRITE: encryptForBytea(plaintext, aad.<builder>(...)) → goes into the _enc column.
       NEVER pass a raw encrypt() Buffer to Supabase JS — it JSON-wraps the bytes.
       Write ONLY the _enc column. Plaintext counterparts no longer exist.
       For tables where AAD uses row id but id is generated by Postgres, use the
       2-step insert pattern: insert minimal row → read id → update with _enc.
READ:  decryptColumn(row.column_enc, aad.<builder>(...))
       Throws on null/invalid. decryptOrFallback is the Phase 1 transition helper,
       kept only for legacy code paths — use decryptColumn in all new code.

Encrypted columns (the only form these fields exist in now):
  Phase 1+2 (content + tokens):
    messages.subject_enc
    embeddings.keyword_text_enc
    drive_embeddings.keyword_text_enc
    asana_embeddings.keyword_text_enc
    summaries.summary_enc
    facts.detail_enc
    oauth_tokens.access_token_enc
    oauth_tokens.refresh_token_enc
  Phase 3a (PII + metadata):
    messages.sender_enc
    messages.thread_id_enc
    drive_files.name_enc
    asana_items.name_enc
    asana_items.project_name_enc
    asana_items.assignee_enc
    asana_items.notes_enc
    asana_items.due_date_enc
    asana_items.permalink_url_enc
    workspace_contexts.context_text_enc
  Phase 3b (drift findings):
    drift_findings.decision_summary_enc
    drift_findings.draft_update_enc
    drift_findings.resolution_note_enc
  Phase 4 (workspace + chat):
    workspaces.name_enc
    conversations.title_enc
    conversation_messages.content_enc

AAD builders are in src/lib/crypto-aad.ts. Write side and read side MUST use the
SAME builder for the same (table, column). For free-form string fields in AAD
(type, subject, anything AI-generated), the builder uses \x1f (Unit Separator) —
colons can collide on free-form text. Integer/UUID/enum identity fields use ":".

Tier 3 (still plaintext by design): mime_type, IDs, foreign keys, timestamps,
booleans, enums, role strings, source enums. Anything queryable for FTS/join/
filter at the SQL layer where encryption would break functionality.

Search is vector-only. Postgres FTS (tsvector) cannot operate on bytea.
Decrypt-then-rerank in Node if BM25-style recall is ever needed.

When in doubt, read scripts/verify-final.ts — it enumerates every encrypted
column and verifies the round-trip works end-to-end.

Full design: /Users/mingw/.claude/plans/atomic-crafting-wreath.md
EOF
